server:
  port: 8080


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisGagoGimenez/ConfigServerCloud
          default-label: main
          search-paths:
          - '*property'
