server:
  port: 8888


spring:
  application:
    name: myvalue  cloud:    config:      server:
        git:
          uri: https://github.com/LuisGagoGimenez/ConfigServerCloud
          default-label: main
          search-paths:          - '*service'